name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name:  Checkout 
        uses:  actions/checkout@v4
      - name:  Setup Latest Node
        uses:  actions/setup-node@v4
        with:
          node-version:  20
      - name: Install npm
        run: npm install -g bats
      - name: Test npm
        run: npm test
      - name: run bats
        run: bats -v
