name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name:  Checkout 
        uses:  actions/checkout@v4
      - name:  Setup Latest Node
        uses:  actions/setup-node@v4
        with:
          node-version:  'lts/*'
      - name: Install dependencies
        run: npm install
